### ISSUE TITLE
尝试分析nginx日志遇到错误

### ISSUE THREAD

**Issue by sclodestar** [JeffXue/WebLogParser#6]
大神您好，尝试使用您的日志分析器，把access.log放到data下运行 python start.py遇到下列错误
[root@localhost bin]# python start.py
2021-04-30 15:59:00.200930  Start parse file : access.log
Traceback (most recent call last):
  File "/home/web-log-parser-master/bin/start.py", line 381, in main
    parse_log_file(target_file, log_format)
  File "/home/web-log-parser-master/bin/start.py", line 232, in parse_log_file
    response_avg = int(pv / len(set(times)))
ZeroDivisionError: division by zero

问一下是哪里没有设置呢？谢谢您。

**Comment by JeffXue** [comment]
前面解析到的times的数据为空，初步考虑是日志格式的正则配置有问题，请检查下配置文件config.ini的配置log-pattern和log-format

**Comment by sclodestar** [comment]
大概明白意思了

**Comment by sclodestar** [comment]
我不会写正则表达式，我的nginx日志是这样的格式，请大神帮写一下log-pattern和log-format

log如下
-----------------------
171.105.148.164 - - [10/May/2021:18:34:12 +0800] "GET /pda/workflow/turn.php?RUN_ID=88559&FLOW_ID=38&PRCS_ID=4&FLOW_PRCS=4&PRCS_KEY_ID=478746&FLOW_TYPE=1&_=1620642851736 HTTP/1.1" 200 4234 "http://oa.gmyh.com.cn/pda/workflow/handle.php?RUN_ID=88559&FLOW_ID=38&PRCS_ID=4&FLOW_PRCS=4&PRCS_KEY_ID=478746&EDIT_FLAG=1&actionType=handle&FLOW_ID_NEW=" "Mozilla/5.0 (Linux; Android 10; CLT-AL00 Build/HUAWEICLT-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36TDOA_Android"
171.105.148.164 - - [10/May/2021:18:37:41 +0800] "POST /mobile/push.php HTTP/1.1" 200 45 "-" "okhttp/3.14.1"
171.105.148.164 - - [10/May/2021:18:37:56 +0800] "GET /pda/workflow/sign_submit.php?P=113%3B6vvbqb3q3ilr7sdfaossqmpq60%3B6&RUN_ID=88559&FLOW_ID=38&PRCS_ID=4&FLOW_PRCS=4&PRCS_KEY_ID=478746&CONTENT=%E5%90%8C%E6%84%8F%E3%80%82&SIGN_ATTACH=%7B%22attach_id%22%3A%22%22%2C%22attach_name%22%3A%22%22%7D&_=1620643076133 HTTP/1.1" 404 564 "http://oa.gmyh.com.cn/pda/workflow/handle.php?RUN_ID=88559&FLOW_ID=38&PRCS_ID=4&FLOW_PRCS=4&PRCS_KEY_ID=478746&EDIT_FLAG=1&actionType=handle&FLOW_ID_NEW=" "Mozilla/5.0 (Linux; Android 10; CLT-AL00 Build/HUAWEICLT-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36TDOA_Android"
171.105.148.164 - - [10/May/2021:18:37:57 +0800] "GET /pda/workflow/turn.php?RUN_ID=88559&FLOW_ID=38&PRCS_ID=4&FLOW_PRCS=4&PRCS_KEY_ID=478746&FLOW_TYPE=1&_=1620643076244 HTTP/1.1" 200 4234 "http://oa.gmyh.com.cn/pda/workflow/handle.php?RUN_ID=88559&FLOW_ID=38&PRCS_ID=4&FLOW_PRCS=4&PRCS_KEY_ID=478746&EDIT_FLAG=1&actionType=handle&FLOW_ID_NEW=" "Mozilla/5.0 (Linux; Android 10; CLT-AL00 Build/HUAWEICLT-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36TDOA_Android"
----------------------------------------------------------

谢谢您
